
# Site settings

url: "https://0xnacho.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

baseurl: https://0xnacho.github.io

# Google tracking id to track your visitors

google-tracking-id: "UA-70177721-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

#############
# HTML Head #
#############

author: "Nacho García (0xNacho)"
lang: "es"
title: "{ 0xNacho }"
favicon: "/img/favicon.ico"
description: "Blog and website of 0xNacho, blogging mainly for tech. Opinions expressed are mine."
keywords: "0xnacho, nacho garcia, personal , jekyll"

################
# Intro layout #
################

black-favicon: "/img/black-lab-glass.ico"
background-img: "../img/intro-bg.jpg"
me-img: "/img/jetpacktocat.png"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: True	# Shuffle the lines.
loop: True
loop-count:	False # Set False for infinite loop, or set any number for finite loop.
type-speed:	10		# Default 10
start-delay: 200	# Default 200
delete-delay: 5000	# Default 5000
lines:			# You can add HTML Tags in the Text
  - text: "My Rules:"
  - text: "1º Javascript = &lt;3"
  - text: "2º The quieter you become, the more you are able to hear. (#Kali)"

########
# Blog #
########

post-preview-words: 96

paginate: 5

fb-share: True
twitter-share: True
reddit-share: True
google-plus-share: True
linkedin-share: True
pinterest-share: True
vkontakte-share: True
disqus-shortname: "0xNacho"

###############
# Life Events #
###############

events:
  - image: "/img/career/spidertocat.png"
    date: "September 2015 - Today"
    description: "Lecturer of Master in Big Data Architecture (NoSQL, MongoDB)"
  - image: "/img/jetpacktocat.jpg"
    date: "November 2012 - Today"
    description: "Treelogic S.L."

  - image: "/img/treelogic.jpg"
    date: "December 1991 - Today"
    description: "Hey! I was born!"


# First image of the Career timeline
career-img: "/img/career/default.png"

##################
# Contact layout #
##################

email: "0xnacho@gmail.com"

##################
# Social Buttons #
##################

social:
  - title: "twitter"
    url: "https://twitter.com/0xNacho"
  - title: "github"
    url: "https://github.com/0xNacho"
  - title: "linkedin"
    url: "https://www.linkedin.com/profile/view?id=AAMAAA4-m3sBwxYZ1luASSBdSXPgzju7Cl_W0Uc"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Exclusion list from the generated _site

exclude: ["LICENSE", "README", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems: [jekyll-paginate]
